### Cohen's kappa for sport and art users' posts between Yuval and Valerie

In [8]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

# Load the files
file = 'posts20.xlsx' 

# Read the files
df1 = pd.read_excel(file, sheet_name="sport and art users posts")


# Extract the relevant columns
Yuval_grade_1 = df1["Yuval's grade1"] 
Yuval_grade_2 = df1["Yuval's grade2"] 
Val_grade_1 = df1["Val's grade1"] 
Val_grade_2 = df1["Val's grade2"] 

# Ensure the columns have the same length
if len(Yuval_grade_1) != len(Yuval_grade_2) or len(Val_grade_1) != len(Val_grade_2):
    raise ValueError("Columns do not have the same number of entries.")

# Calculate Cohen's kappa
kappa_sport_and_art_grade_1 = cohen_kappa_score(Yuval_grade_1, Val_grade_1)
kappa_sport_and_art_grade_2 = cohen_kappa_score(Yuval_grade_2, Val_grade_2)

# Print the results
print("Kappa for Grade 1 (Sport and Art):", kappa_sport_and_art_grade_1)
print("Kappa for Grade 2 (Sport and Art):", kappa_sport_and_art_grade_2)


Kappa for Grade 1 (Sport and Art): 0.8461538461538461
Kappa for Grade 2 (Sport and Art): 1.0


### Cohen's kappa for only art users posts between Yuval and Valerie

In [7]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

# Load the files
file = 'posts20.xlsx' 

# Read the files
df1 = pd.read_excel(file, sheet_name="only art users posts")


# Extract the relevant columns
Yuval_grade_1 = df1["Yuval's grade1"] 
Yuval_grade_2 = df1["Yuval's grade2"] 
Val_grade_1 = df1["Val's grade1"] 
Val_grade_2 = df1["Val's grade2"] 

# Ensure the columns have the same length
if len(Yuval_grade_1) != len(Yuval_grade_2) or len(Val_grade_1) != len(Val_grade_2):
    raise ValueError("Columns do not have the same number of entries.")

# Calculate Cohen's kappa
kappa_sport_and_art_grade_1 = cohen_kappa_score(Yuval_grade_1, Val_grade_1)
kappa_sport_and_art_grade_2 = cohen_kappa_score(Yuval_grade_2, Val_grade_2)

# Print the results
print("Kappa for Grade 1 (Only Art):", kappa_sport_and_art_grade_1)
print("Kappa for Grade 2 (Only Art):", kappa_sport_and_art_grade_2)


Kappa for Grade 1 (Only Art): 0.8387096774193548
Kappa for Grade 2 (Only Art): 0.8305084745762712


### Cohen's kappa for sport and art users' posts between GPT and Valerie

In [ ]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

# Load the files
file = 'posts20_tagged_with_GPT4.xlsx' 

# Read the files
df1 = pd.read_excel(file, sheet_name="sport and art users posts")


# Extract the relevant columns
GPT_grade_1 = df1["GPT Grade1"] 
GPT_grade_2 = df1["GPT Grade2"] 
Val_grade_1 = df1["Val's grade1"] 
Val_grade_2 = df1["Val's grade2"] 

# Ensure the columns have the same length
if len(GPT_grade_1) != len(GPT_grade_2) or len(Val_grade_1) != len(Val_grade_2):
    raise ValueError("Columns do not have the same number of entries.")

# Calculate Cohen's kappa
kappa_sport_and_art_grade_1 = cohen_kappa_score(GPT_grade_1, Val_grade_1)
# kappa_sport_and_art_grade_2 = cohen_kappa_score(GPT_grade_2, Val_grade_2)

# Print the results
print("Kappa for Grade 1 (Sport and Art):", kappa_sport_and_art_grade_1)
print("Kappa for Grade 2 (Sport and Art):", kappa_sport_and_art_grade_2)


Kappa for Grade 1 (Sport and Art): 0.3827160493827162
Kappa for Grade 2 (Sport and Art): 1.0


In [13]:
import pandas as pd
import numpy as np
from statsmodels.stats.inter_rater import fleiss_kappa

# Example DataFrame
data = {
    "GPT Grade1": GPT_grade_1,
    "Val's grade1": Val_grade_1,
    "yuval's grade1": Yuval_grade_1
}
df1 = pd.DataFrame(data)

# Step 1: Identify all unique categories
categories = sorted(set(df1["GPT Grade1"].unique())
                    | set(df1["Val's grade1"].unique())
                    | set(df1["yuval's grade1"].unique()))

# Step 2: Create a matrix of counts for each item
counts = []
for i, row in df1.iterrows():
    row_counts = [list(row).count(category) for category in categories]
    counts.append(row_counts)

# Convert to a NumPy array
counts_matrix = np.array(counts)

# Step 3: Calculate Fleiss' Kappa
kappa = fleiss_kappa(counts_matrix, method='fleiss')

# Print the results
print("Categories:", categories)
print("Counts Matrix:\n", counts_matrix)
print("Fleiss' Kappa:", kappa)


Categories: ['Rather productive', 'rather neutral', 'rather not productive', 'rather productive', 'subject has rather nothing to do with productivity']
Counts Matrix:
 [[0 2 0 0 1]
 [0 0 3 0 0]
 [0 2 0 0 1]
 [0 0 0 3 0]
 [0 0 3 0 0]
 [0 2 1 0 0]
 [0 0 2 0 1]
 [0 2 1 0 0]
 [1 2 0 0 0]
 [0 0 0 3 0]]
Fleiss' Kappa: 0.4495412844036695
